### ISSUE TITLE
Error: LDAP extension not loaded

### ISSUE THREAD

**Issue by chelming** [digihum/omeka-s-ldap#2]
```
exception 'Zend\Ldap\Exception\LdapException' with message '0x7002: LDAP extension not loaded' in /test/omeka-s/modules/LDAP/vendor/zendframework/zend-ldap/src/Ldap.php:79
```
I get this message trying to authenticate after activating the plugin. Is there a step I missed?

**Comment by chelming** [comment]
I _do_ have php-ldap installed and according to `php -i` ldap support is enabled.

**Comment by chelming** [comment]
I'm dumb and forgot to restart Apache after installing php-ldap.

The shame! 😞

**Comment by TimHollies** [comment]
No worries - glad you sorted it :)
