### ISSUE TITLE
php error

### ISSUE THREAD

**Issue by mopwr** [digihum/omeka-s-ldap#4]
When installing there is a problem with module.php

Warning: require(/var/www/html/omeka-s/modules/Ldap/vendor/autoload.php): failed to open stream: No such file or directory in /var/www/html/omeka-s/modules/Ldap/Module.php on line 4

Fatal error: require(): Failed opening required '/var/www/html/omeka-s/modules/Ldap/vendor/autoload.php' (include_path='.:/usr/share/php') in /var/www/html/omeka-s/modules/Ldap/Module.php on line 4

**Comment by denseflux** [comment]
The vendor folder is created by running 'composer install' from the root folder of the Ldap module (where the composer.json for the Ldap module exists) - in your case you need to run that command from within /var/www/omeka-s/modules/Ldap.
